name: CI Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Ensure Chrome is installed
        run: |
          if ! command -v google-chrome-stable &> /dev/null; then
            echo "Google Chrome not found, installing..."
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
          fi

      - name: Set CHROME_PATH
        run: echo "CHROME_PATH=/usr/bin/google-chrome" >> $GITHUB_ENV
        
      - name: Run tests
        run: npm run test:ci
